name: matsciml
channels:
  - defaults
  - intel
  - dglteam
dependencies:
  - intel::pytorch=2.1.0
  - intel::intel_extension_for_pytorch=2.1.10
  - intel::scipy
  - intel::numba
  - dglteam::dgl=2.0.0
  - setuptools
  - pybind11
  - pip
  - pip:
      - "-e './[all]'"
